server:
  port: 8104

spring:
  application:
    name: admission-service
  datasource:
    url: jdbc:sqlite:./data/admission.db?busy_timeout=60000&journal_mode=WAL
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false

app:
  school-service:
    base-url: http://localhost:8102
  student-service:
    base-url: http://localhost:8103
  auth-service:
    base-url: http://localhost:8101
  admin:
    username: admin
    password: admin123
  jwt:
    secret: gqm2026-dongcheng-exam-simulation-secret-key-2026

